/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#003640",
        "secondary-container": "#0566d9",
        "inverse-primary": "#732ee4",
        "surface-container-high": "#272a31",
        "tertiary-container": "#007184",
        "secondary-fixed": "#d8e2ff",
        "outline": "#958da1",
        "secondary": "#adc6ff",
        "inverse-surface": "#e1e2eb",
        "on-tertiary-fixed": "#001f26",
        "surface-bright": "#363940",
        "tertiary": "#4cd7f6",
        "on-background": "#e1e2eb",
        "background": "#10131a",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-primary-container": "#ede0ff",
        "on-secondary-fixed-variant": "#004395",
        "on-surface-variant": "#ccc3d8",
        "on-tertiary-container": "#b7efff",
        "surface-container-lowest": "#0b0e14",
        "on-secondary-container": "#e6ecff",
        "surface-variant": "#32353c",
        "outline-variant": "#4a4455",
        "surface-dim": "#10131a",
        "primary-fixed-dim": "#d2bbff",
        "inverse-on-surface": "#2e3037",
        "primary-fixed": "#eaddff",
        "surface-container-low": "#191c22",
        "tertiary-fixed": "#acedff",
        "surface": "#10131a",
        "surface-container": "#1d2026",
        "on-secondary": "#002e6a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed": "#25005a",
        "surface-tint": "#d2bbff",
        "primary-container": "#7c3aed",
        "surface-container-highest": "#32353c",
        "error": "#ffb4ab",
        "on-surface": "#e1e2eb",
        "on-error": "#690005",
        "on-primary": "#3f008e",
        "primary": "#d2bbff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding-desktop": "40px",
        "stack-md": "16px",
        "gutter": "24px",
        "unit": "4px",
        "container-padding-mobile": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
